#!/usr/bin/env bash

########################################################
#
# Run the fio scripts generated by generate-cache-finder
#
########################################################
help() { echo "$0 -d <fio files dir> (The directory containing the fio files)" ; exit 0 ;}
while getopts ":d:hv" Option
do
    case $Option in
        d   )   OUTPUTDIR=$OPTARG ;;
        h   )   help ;;
        v   )   VERBOSE=1 ;;
        ?   )   echo "Unknown argument $OPTARG" ; exit ;;
    esac
done
if [ ! -z $OUTPUTDIR  ]; then echo "The fio directory is $OUTPUTDIR" 
else
	echo "No Directory provided.  Use -o to point to a directory containing fio files."
	exit 1
fi

pushd .
cd $OUTPUTDIR
for script in $(ls *.fio|sort -n)
do
    echo fio $script --output-format=json -o $script.out.json
    fio $script --output-format=json -o $script.out.json
done
popd
